### PR TITLE
Added Platform/ and Compiler/ dirs, modify MODULE_PATH to find them.

### PR DESCRIPTION
**Pull request by xhuw**
Hey, 

Surprise PR for you 😄 The main changes below are the creation of the three empty files in `Compiler/` and `Platform/`, and adding those directories to the `CMAKE_MODULE_PATH`. This means it will find them when cmake goes looking for these files!

I also added a test which verifies there are no warnings for simple C, C++, XC and S source files.

### CODE REVIEW

**Comment by xhuw** [comment]
@keithm-xmos That does seem like it would be the proper way. Perhaps we could go with the change proposed here AND set the value of CMAKE_SYSTEM_PROCESSOR. And then we can begin slowly moving to the new way.

The context is that our project is about to be released and the current warnings don't give the greatest first impressions and are likely to result in users raising issues.

**Comment by xhuw** [comment]
> I believe the `Warning: Did not find file Compiler/-ASM` warnings can be removed by simply adding the following line to the xs3a.cmake and xs2a.cmake files.
> 
> `set(CMAKE_ASM_COMPILER_ID "Clang")`

tried this and it does work as you suggested it would. I can delete the `Compiler/` directory and make that change to replace it if that is preferable

**Comment by keithm-xmos** [comment]
I am OK with doing this incrementally.

**Comment by xhuw** [comment]
Agree that setting source file extensions is a good idea. just tried a `.asm` file and XCC gives the following:

```
[ 50%] Building ASM object CMakeFiles/asm.dir/asm.asm.obj
/home/huw/projects/sw_xvf3800/xcore_sdk/xmos_cmake_toolchain/test/test_app/asm.asm: linker input file unused because linking not done


[ 75%] Linking ASM executable asm.xe
xcc: CMakeFiles/asm.dir/asm.asm.obj: No such file or directory
gmake[2]: *** [CMakeFiles/asm.dir/build.make:96: asm.xe] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:251: CMakeFiles/asm.dir/all] Error 2

```

so `s;S` is our supported ASM file extensions. If I set this it will make cmake fail if someone passes in a `.asm` file as a source for a library/executable

**Review by keithm-xmos — APPROVED** [review]

**Review by xmos-jmccarthy — APPROVED** [review]

**Pull request merged**
